/**
 * BOROUGH PAGE — Tower Hamlets
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:42:54
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172878/vigil/security/service/construction-site-security-london-vigil-security-services-security-london.webp",
    alt:    "Vigil security officer in hi-vis jacket with SIA licence and CSCS hard hat using handheld device at London construction site",
    width:  1234,
    height: 864,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172878/vigil/security/service/construction-site-security-london-vigil-security-services-security-london.webp",
    alt:    "Vigil security officer in hi-vis jacket with SIA licence and CSCS hard hat using handheld device at London construction site",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Tower Hamlets?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and concierge services across all Tower Hamlets postcodes including E1, E2, E14. Our SIA-licensed officers are deployed to corporate offices in Canary Wharf (see our dedicated Canary Wharf page), construction sites across major regeneration projects, docklands developments and warehouse conversions, retail premises, tech and creative industry hubs around Shoreditch and Whitechapel, healthcare facilities, and residential developments. All officers are directly employed by Vigil, DBS-checked, and trained in access control, incident response, conflict management, and first aid. We provide both scheduled contracts and emergency callouts with 24/7 availability across Tower Hamlets\'s diverse commercial zones.'
  },
  {
    question: 'Do you cover Canary Wharf in Tower Hamlets?',
    answer: 'Yes. We provide comprehensive security services to Canary Wharf and the wider Tower Hamlets area. However, given Canary Wharf\'s unique concentration of corporate finance, high-rise office buildings, and 24/7 business operations, we have created a dedicated Canary Wharf commercial security page covering services specific to the E14 financial district. For corporate offices, high-rise buildings, and financial services premises in Canary Wharf, please see our dedicated page. This page covers the wider Tower Hamlets area including Bethnal Green, Whitechapel, Bow, Poplar, Limehouse, and Isle of Dogs residential and mixed-use developments, construction sites, and retail premises.'
  },
  {
    question: 'Do you provide construction site security in Tower Hamlets?',
    answer: 'Yes. Tower Hamlets is experiencing extensive construction activity including major residential and mixed-use developments around Canary Wharf fringe, Isle of Dogs, and Poplar, regeneration projects in Whitechapel and Bow, warehouse conversions across the docklands, and infrastructure projects including Crossrail sites and transport upgrades. Vigil provides specialist construction site security including 24/7 gatehouse manned by SIA-licensed officers trained in CDM 2015 protocols, mobile patrols for unstaffed hours, tool audits, PPE enforcement, visitor sign-in and contractor verification, and alarm response. Officers understand construction site hazards, welfare obligations, and project timeline pressures. We serve main contractors, developers, and project managers operating across Tower Hamlets from small infill residential sites to major mixed-use developments. See our dedicated construction site security page for full details.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Tower Hamlets | B2B Contracts | Vigil',
    description:  'Commercial security Tower Hamlets. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-tower-hamlets/',
    focusKeyword: 'commercial security tower hamlets',
  },
  borough:      'Tower Hamlets',
  region:       'East London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Tower Hamlets. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Tower Hamlets. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Tower Hamlets is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Tower Hamlets', description: 'Scheduled security for Tower Hamlets offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Tower Hamlets.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Tower Hamlets contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Tower Hamlets quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
