/**
 * BOROUGH PAGE — Barnet
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:50:52
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172918/vigil/security/service/retail-guard-vigil-security-services-security-london.webp",
    alt:    "SIA-licensed security guard on duty at retail store entrance on Oxford Street, London",
    width:  1234,
    height: 864,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172918/vigil/security/service/retail-guard-vigil-security-services-security-london.webp",
    alt:    "SIA-licensed security guard on duty at retail store entrance on Oxford Street, London",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Barnet?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and concierge services across all Barnet postcodes including NW4, N12, EN5. Our SIA-licensed officers are deployed to corporate offices, retail premises, construction sites, healthcare facilities, educational institutions, and residential developments. All officers are directly employed by Vigil, DBS-checked, and trained in access control, incident response, conflict management, and first aid. We provide both scheduled contracts and emergency callouts with 24/7 availability across Greater London.'
  },
  {
    question: 'Are your Barnet security officers SIA-licensed?',
    answer: 'Yes. Every officer deployed to Barnet holds a current SIA licence in the appropriate category — Security Guarding, Door Supervision, or CCTV Operations. The Security Industry Authority regulates private security in the UK and mandates licensing for all frontline officers. All licences are verified at recruitment and renewed every three years. We do not use agency staff or sub-contractors. Every guard assigned to a Barnet contract is directly employed by Vigil, ensuring accountability, consistency, and adherence to our service standards. Officers are familiar with Barnet geography, local transport links, and common commercial security challenges in the borough.'
  },
  {
    question: 'How quickly can you mobilise security services in Barnet?',
    answer: 'For standard manned guarding or mobile patrol contracts in Barnet, we typically mobilise within 48–72 hours of contract signature. This includes conducting a site risk assessment, assigning officers, completing site-specific training, and issuing uniforms and equipment. For emergency deployments — such as following a break-in, vandalism incident, or sudden staff absence — we maintain a pool of trained relief officers and can often deploy to Barnet sites within 24 hours. For key holding and alarm response services, we can usually activate your account within 24 hours once we hold your site keys and alarm codes. Complex sites requiring detailed risk assessments or specialist vetting may require 5–7 working days for mobilisation.'
  },
  {
    question: 'What areas of Barnet do you cover?',
    answer: 'Vigil Security covers all Barnet postcodes including NW4, N12, EN5 and surrounding areas. We deploy officers to commercial zones such as Finchley office parks, retail premises along the A1000 and A41 corridors, construction sites across new-build residential and commercial developments, healthcare facilities, schools and colleges, and residential buildings requiring concierge or door supervision services. Barnet is one of London\'s largest boroughs by area, and our officers are familiar with its commercial districts, transport hubs, and business parks. We also serve multiple sites across Barnet and neighbouring boroughs under consolidated contracts for clients with London-wide operations.'
  },
  {
    question: 'Do you provide construction site security in Barnet?',
    answer: 'Yes. Vigil provides specialist construction site security for main contractors, developers, and project managers operating in Barnet. Our officers are trained in CDM 2015 site welfare obligations, tool audits, PPE enforcement, and visitor management protocols specific to construction environments. We provide 24/7 site security, gatehouse access control, mobile patrols for unstaffed hours, and alarm response services. Barnet has seen significant residential and commercial development in recent years, particularly around Colindale, Brent Cross, and Mill Hill, and we have extensive experience securing construction sites of all sizes from small infill plots to major mixed-use developments. See our dedicated construction site security page for full details.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Barnet | B2B Contracts | Vigil',
    description:  'Commercial security Barnet. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-barnet/',
    focusKeyword: 'commercial security barnet',
  },
  borough:      'Barnet',
  region:       'North London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Barnet. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Barnet. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Barnet is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Barnet', description: 'Scheduled security for Barnet offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Barnet.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Barnet contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Barnet quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
