/**
 * SERVICE PAGE — Manned Guarding London
 * Template: ServicePage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }  from 'next'
import ServicePage    from '@/components/templates/ServicePage'
import { generateServicePageSchema } from '@/lib/schema/service-page-schema'
import type { ServicePageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:51:09
// Manage at: app.vigilservices.co.uk/admin/pages
const images: ServicePageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
    priority: true,
  },
  intro: {
    src:    "/placeholder-image.svg",
    alt:    "Intro image — assign via CRM",
    width:  600,
    height: 400,
  },
  step1: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 1 — assign via CRM",
    width:  400,
    height: 300,
  },
  step2: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 2 — assign via CRM",
    width:  400,
    height: 300,
  },
  step3: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 3 — assign via CRM",
    width:  400,
    height: 300,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  caseStudy: {
    src:    "/placeholder-image.svg",
    alt:    "Case study image — assign via CRM",
    width:  800,
    height: 450,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What does a manned guarding service include?',
    answer: 'Manned guarding provides SIA-licensed security officers stationed at your premises during operating hours or 24/7. Officers conduct access control, visitor management, CCTV monitoring, regular patrols of the site perimeter and interior, incident response, and detailed shift reports. All our officers are directly employed by Vigil, DBS-checked, and trained in conflict management, first aid, and fire safety. You receive the same assigned officers on a consistent rota, ensuring they know your site, your staff, and your security protocols intimately.'
  },
  {
    question: 'Are all your security officers SIA-licensed?',
    answer: 'Yes. Every officer deployed to your site holds a current SIA licence in the appropriate category — either Security Guarding or Door Supervision. The SIA (Security Industry Authority) is the regulatory body for private security in the UK. All licences are checked at recruitment and renewed every three years. We do not use agency staff or sub-contracted officers. Every guard on a Vigil contract is a directly employed member of our team, ensuring accountability, consistency, and adherence to our service standards.'
  },
  {
    question: 'What is the difference between manned guarding and mobile patrols?',
    answer: 'Manned guarding places a dedicated officer on your premises for the duration of the shift — typically 8, 10, or 12 hours, or 24/7 depending on your requirements. The officer remains on-site, providing continuous visible deterrence and immediate response to any incident. Mobile patrols involve periodic visits to your site at agreed intervals (e.g., 2–4 times per shift), with officers spending 15–30 minutes per visit conducting external and internal checks. Manned guarding is suited to higher-risk sites, premises with high footfall, or where access control and visitor management are required. Mobile patrols are cost-effective for lower-risk sites that benefit from regular checks but do not require constant presence.'
  },
  {
    question: 'Can we have the same officers on a regular rota?',
    answer: 'Yes. Consistency is central to our service model. We assign dedicated officers to your site and maintain a stable rota. You will typically have 2–3 assigned officers who rotate shifts, ensuring you always see familiar faces. Officers learn your premises layout, your operational procedures, your staff, and any site-specific risks. This continuity improves security effectiveness and builds trust with your team. If an assigned officer is unavailable due to leave or sickness, we provide a trained relief officer who is briefed on your site before deployment.'
  },
  {
    question: 'What areas of London do you cover?',
    answer: 'Vigil Security operates across Greater London, from the City of London and Canary Wharf to outer boroughs including Barnet, Bromley, and Hillingdon. We deploy officers to commercial offices, retail premises, construction sites, healthcare facilities, educational institutions, and residential developments. All officers are familiar with London geography and transport links. If your organisation operates multiple sites across London, we can provide manned guarding under a single contract with consolidated reporting and one account manager.'
  },
  {
    question: 'How quickly can you mobilise manned guarding for our site?',
    answer: 'For standard deployments, we can typically mobilise within 48–72 hours of contract signature. This includes conducting a site risk assessment, assigning officers, completing site-specific training, and issuing uniforms and equipment. For emergency deployments — for example, following a security incident or sudden staff absence — we maintain a pool of trained relief officers and can often deploy within 24 hours. For complex sites requiring detailed risk assessments or specialist vetting, mobilisation may take 5–7 working days. We will confirm timelines during the initial consultation.'
  }
]

const pageData: ServicePageData = {
  seo: {
    title:        'Manned Guarding London | SIA-Licensed Security Officers',
    description:  'manned guarding London — SIA-licensed officers, directly employed, £10M insured. Professional on-site security for offices, retail, and commercial premises across Greater London.',
    canonical:    'https://security.vigilservices.co.uk/manned-guarding-london',
    focusKeyword: 'manned guarding london',
  },
  h1:          'Manned Guarding London',
  subheadline: 'SIA licensed. BS7858 vetted. 15-minute response. Greater London.',
  quickAnswer: 'Vigil Security Services provides manned guarding london exclusively to businesses across Greater London. Every officer is directly employed — never agency supplied.',
  intro:       '<p>Vigil Security Services works exclusively with businesses across Greater London. Every officer is directly employed by Vigil Services Ltd — SIA-licensed, BS7858 vetted, and consistently assigned to your contract.</p>',
  services:    [],
  processSteps: [
    { number: 1, title: 'Contact Vigil',
       description: 'Call or complete the enquiry form. We respond within 15 minutes.',
       timeframe: 'Within 15 minutes' },
    { number: 2, title: 'Site risk assessment',
       description: 'We visit your premises, assess your security requirements, and produce a written specification.',
       timeframe: 'Within 48 hours' },
    { number: 3, title: 'Officers deployed',
       description: 'Your directly employed, SIA-licensed team begins on your agreed start date.',
       timeframe: 'As agreed' },
  ],
  eeatPoints:    [
    { icon: '🪪', title: 'SIA-licensed officers', description: 'Every officer holds a current SIA licence in the appropriate category — Security Guarding or Door Supervision.' },
    { icon: '🔒', title: 'BS7858 vetted', description: 'Full 5-year employment history check and ID verification before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital shift reports', description: 'Timestamped shift logs and incident reports after every deployment.' },
  ],
  complianceTags: ['SIA Licensed', 'BS7858 Vetted', 'DBS Enhanced', 'Directly Employed',
                   '£10M Insured', 'PSIA 2001', 'Company Reg. 11756806'],
  boroughLinks:  [],
  faqs,
  cta: {
    primaryLabel: 'Get a security quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateServicePageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <ServicePage data={pageData} />
    </>
  )
}
