/**
 * SERVICE PAGE — Event Security London
 * Template: ServicePage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }  from 'next'
import ServicePage    from '@/components/templates/ServicePage'
import { generateServicePageSchema } from '@/lib/schema/service-page-schema'
import type { ServicePageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:51:07
// Manage at: app.vigilservices.co.uk/admin/pages
const images: ServicePageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172932/vigil/security/service/security-guard-event-service-security-london.webp",
    alt:    "Security team in branded jackets providing manned guarding on a London street",
    width:  7500,
    height: 5000,
    priority: true,
  },
  intro: {
    src:    "/placeholder-image.svg",
    alt:    "Intro image — assign via CRM",
    width:  600,
    height: 400,
  },
  step1: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 1 — assign via CRM",
    width:  400,
    height: 300,
  },
  step2: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 2 — assign via CRM",
    width:  400,
    height: 300,
  },
  step3: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 3 — assign via CRM",
    width:  400,
    height: 300,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  caseStudy: {
    src:    "/placeholder-image.svg",
    alt:    "Case study image — assign via CRM",
    width:  800,
    height: 450,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172932/vigil/security/service/security-guard-event-service-security-london.webp",
    alt:    "Security team in branded jackets providing manned guarding on a London street",
    width:  7500,
    height: 5000,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What is event security and what does it include?',
    answer: 'Event security provides SIA-licensed Door Supervisors and security officers to manage safety, access control, and crowd management at events. Services include guest list verification, bag searches, ID checks, ticket validation, stewarding, VIP protection, conflict de-escalation, emergency evacuation coordination, and liaison with police or emergency services if required. Event security is essential for corporate conferences, product launches, private parties, charity galas, outdoor festivals, sporting events, and any gathering where public safety, access control, or licensing obligations require professional security presence. All Vigil event officers hold current SIA Door Supervision licences and are trained in crowd dynamics, conflict management, and first aid.'
  },
  {
    question: 'Do all event security officers need SIA licences?',
    answer: 'Yes. Any security officer working at a licensed premises (venues selling alcohol under the Licensing Act 2003) or conducting door supervision duties (controlling entry, searching patrons, ejecting individuals) must hold a current SIA Door Supervision licence. SIA licensing is a legal requirement under the Private Security Industry Act 2001. Unlicensed security at licensed premises can result in prosecution of both the venue and the individual, plus potential loss of the premises licence. Vigil only deploys SIA-licensed officers to events. We verify every officer\'s licence at recruitment, monitor expiry dates, and ensure renewals are completed before deployment. Clients can request sight of any officer\'s SIA badge on arrival at the event.'
  },
  {
    question: 'What types of events do you provide security for?',
    answer: 'Vigil provides event security for corporate events (conferences, product launches, AGMs, awards ceremonies), private functions (weddings, birthday parties, anniversary celebrations), charity galas and fundraisers, networking events and trade shows, outdoor festivals and concerts, sporting events (marathons, boxing matches, football tournaments), nightclub and bar events, film premieres and red-carpet events, and religious or cultural gatherings. Each event type has specific security requirements — corporate events require discreet, professionally presented officers; outdoor festivals require crowd management and perimeter control; private functions require guest list management and conflict de-escalation. We tailor officer deployment, uniform style, and operational procedures to suit the nature and tone of your event.'
  },
  {
    question: 'How many security officers do we need for our event?',
    answer: 'The number of officers required depends on event size, venue layout, alcohol service, audience profile, and licensing requirements. As a general guide: events with 50–100 guests typically require 2 officers, 100–200 guests require 3–4 officers, 200–500 guests require 5–8 officers, and larger events require proportionate scaling. However, venue licensing conditions often mandate minimum officer ratios — for example, 1 officer per 100 guests at licensed premises, or 1 officer per entry/exit point. We conduct a free pre-event site visit to assess the venue, review your event plan, and recommend appropriate staffing levels. Our recommendation is documented in the quotation and considers your event risk assessment, licensing obligations, and budget.'
  },
  {
    question: 'Can you provide event security at short notice?',
    answer: 'Yes. Vigil maintains a pool of trained event security officers available for short-notice deployments. For standard events (corporate functions, private parties), we can typically mobilise within 48–72 hours of booking confirmation. For emergency situations — for example, replacing a cancelled security provider or responding to last-minute licensing authority requirements — we can often deploy officers within 24 hours. However, we recommend booking event security at least 2–3 weeks in advance to ensure availability, conduct a thorough site assessment, and complete pre-event planning. For large or complex events requiring 10+ officers, longer lead times (4–6 weeks) are recommended to secure sufficient staffing and coordinate with venue management and emergency services.'
  },
  {
    question: 'Do you provide event security outside Greater London?',
    answer: 'Our primary operating area is Greater London and we deploy most event security within the M25. However, we can provide event security at venues within approximately 30 miles of central London, including locations in Essex, Hertfordshire, Surrey, and Kent. For events outside this radius, we assess feasibility on a case-by-case basis, considering travel time, officer availability, and whether the event size justifies deployment. If your event is located outside our standard operating area but you prefer continuity with Vigil (for example, because we provide your regular security services in London), contact us to discuss options. We may be able to accommodate one-off deployments for existing clients.'
  }
]

const pageData: ServicePageData = {
  seo: {
    title:        'Event Security London | SIA-Licensed Event Security Officers',
    description:  'event security London — SIA-licensed Door Supervisors and event security officers for corporate events, private functions, and public gatherings across Greater London. £10M insured.',
    canonical:    'https://security.vigilservices.co.uk/event-security-london/',
    focusKeyword: 'event security london',
  },
  h1:          'Event Security London',
  subheadline: 'SIA licensed. BS7858 vetted. 15-minute response. Greater London.',
  quickAnswer: 'Vigil Security Services provides event security london exclusively to businesses across Greater London. Every officer is directly employed — never agency supplied.',
  intro:       '<p>Vigil Security Services works exclusively with businesses across Greater London. Every officer is directly employed by Vigil Services Ltd — SIA-licensed, BS7858 vetted, and consistently assigned to your contract.</p>',
  services:    [],
  processSteps: [
    { number: 1, title: 'Contact Vigil',
       description: 'Call or complete the enquiry form. We respond within 15 minutes.',
       timeframe: 'Within 15 minutes' },
    { number: 2, title: 'Site risk assessment',
       description: 'We visit your premises, assess your security requirements, and produce a written specification.',
       timeframe: 'Within 48 hours' },
    { number: 3, title: 'Officers deployed',
       description: 'Your directly employed, SIA-licensed team begins on your agreed start date.',
       timeframe: 'As agreed' },
  ],
  eeatPoints:    [
    { icon: '🪪', title: 'SIA-licensed officers', description: 'Every officer holds a current SIA licence in the appropriate category — Security Guarding or Door Supervision.' },
    { icon: '🔒', title: 'BS7858 vetted', description: 'Full 5-year employment history check and ID verification before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital shift reports', description: 'Timestamped shift logs and incident reports after every deployment.' },
  ],
  complianceTags: ['SIA Licensed', 'BS7858 Vetted', 'DBS Enhanced', 'Directly Employed',
                   '£10M Insured', 'PSIA 2001', 'Company Reg. 11756806'],
  boroughLinks:  [],
  faqs,
  cta: {
    primaryLabel: 'Get a security quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateServicePageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <ServicePage data={pageData} />
    </>
  )
}
