/**
 * SERVICE PAGE — CCTV Monitoring London
 * Template: ServicePage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }  from 'next'
import ServicePage    from '@/components/templates/ServicePage'
import { generateServicePageSchema } from '@/lib/schema/service-page-schema'
import type { ServicePageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:50:51
// Manage at: app.vigilservices.co.uk/admin/pages
const images: ServicePageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
    priority: true,
  },
  intro: {
    src:    "/placeholder-image.svg",
    alt:    "Intro image — assign via CRM",
    width:  600,
    height: 400,
  },
  step1: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 1 — assign via CRM",
    width:  400,
    height: 300,
  },
  step2: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 2 — assign via CRM",
    width:  400,
    height: 300,
  },
  step3: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 3 — assign via CRM",
    width:  400,
    height: 300,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  caseStudy: {
    src:    "/placeholder-image.svg",
    alt:    "Case study image — assign via CRM",
    width:  800,
    height: 450,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What does CCTV monitoring include?',
    answer: 'Retail security provides SIA-licensed officers stationed at shops to deter security breaches, prevent theft, manage aggressive customers, conduct bag checks, and respond to incidents. Officers are trained in surveillance, conflict de-escalation, reasonable force, and PACE 1984 detention procedures. Retail security is essential for department stores, fashion retailers, supermarkets, electronics stores, and shopping centres experiencing theft or requiring visible deterrence during peak trading.'
  },
  {
    question: 'Can CCTV monitoring officers detain shoplifters?',
    answer: 'Yes, under Section 24A of PACE 1984. SIA-licensed CCTV monitoring officers can make a citizen\'s arrest if they have reasonable grounds to believe theft has occurred. Officers must use only reasonable force, inform the detained person of the arrest grounds, and hand them to police. All detention incidents are documented with witness statements and CCTV evidence. Unlawful detention can result in civil claims, so Vigil officers receive extensive training on legal procedures and evidence requirements.'
  },
  {
    question: 'What is the difference between uniformed security and CCTV operators?',
    answer: 'Uniformed officers wear branded security uniforms and provide visible deterrence at store entrances or high-risk areas. Store detectives wear civilian clothing and covertly observe suspected shoplifters to gather evidence before making an approach. Uniformed officers prevent opportunistic theft; CCTV operators target repeat offenders and organized retail crime. Both must hold SIA licences. Many retailers use a combination for comprehensive surveillance.'
  },
  {
    question: 'How many CCTV monitoring officers do we need?',
    answer: 'Staffing depends on store size, product mix, theft risk, and trading hours. Small stores (under 2,000 sq ft) typically need 1 officer during peak hours. Mid-sized stores (5,000–10,000 sq ft) need 1–2 officers. Large stores or high-value goods retailers may need 2–3 officers plus plainclothes detectives. We conduct free site assessments to review premises layout, historical theft data, and CCTV coverage, then recommend appropriate staffing with documented rationale in the quotation.'
  },
  {
    question: 'Can we have security during peak periods only (Christmas, sales)?',
    answer: 'Absolutely. Many retailers increase security during peak trading when footfall and theft risk are elevated. Vigil provides flexible deployment for Black Friday, Christmas trading (November–January), sales events, and promotional periods. Short-term contracts (1 week to 3 months) available without long-term commitment. Booking 4–6 weeks ahead recommended for peak periods. Existing clients can temporarily increase officer numbers with 2 weeks\' notice.'
  },
  {
    question: 'Do you provide CCTV monitoring for shopping centres?',
    answer: 'Yes. Vigil provides shopping centre security including patrol officers for common areas, CCTV monitoring, anti-social behaviour management, and incident response in tenant stores. For multi-tenanted centres, we offer consolidated security under a single contract covering common areas and selected tenant stores, with unified reporting to centre management. Officers handle opening/closing procedures, manage deliveries, assist shoppers, and coordinate with emergency services.'
  }
]

const pageData: ServicePageData = {
  seo: {
    title:        'CCTV Monitoring London | SIA-Licensed Security | Vigil',
    description:  'CCTV monitoring London — SIA-licensed CCTV monitoring officers and CCTV operators for commercial premises across Greater London. Loss prevention, security breaches deterrence.',
    canonical:    'https://security.vigilservices.co.uk/cctv-monitoring-london/',
    focusKeyword: 'cctv monitoring london',
  },
  h1:          'CCTV Monitoring London',
  subheadline: 'SIA licensed. BS7858 vetted. 15-minute response. Greater London.',
  quickAnswer: 'Vigil Security Services provides cctv monitoring london exclusively to businesses across Greater London. Every officer is directly employed — never agency supplied.',
  intro:       '<p>Vigil Security Services works exclusively with businesses across Greater London. Every officer is directly employed by Vigil Services Ltd — SIA-licensed, BS7858 vetted, and consistently assigned to your contract.</p>',
  services:    [],
  processSteps: [
    { number: 1, title: 'Contact Vigil',
       description: 'Call or complete the enquiry form. We respond within 15 minutes.',
       timeframe: 'Within 15 minutes' },
    { number: 2, title: 'Site risk assessment',
       description: 'We visit your premises, assess your security requirements, and produce a written specification.',
       timeframe: 'Within 48 hours' },
    { number: 3, title: 'Officers deployed',
       description: 'Your directly employed, SIA-licensed team begins on your agreed start date.',
       timeframe: 'As agreed' },
  ],
  eeatPoints:    [
    { icon: '🪪', title: 'SIA-licensed officers', description: 'Every officer holds a current SIA licence in the appropriate category — Security Guarding or Door Supervision.' },
    { icon: '🔒', title: 'BS7858 vetted', description: 'Full 5-year employment history check and ID verification before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital shift reports', description: 'Timestamped shift logs and incident reports after every deployment.' },
  ],
  complianceTags: ['SIA Licensed', 'BS7858 Vetted', 'DBS Enhanced', 'Directly Employed',
                   '£10M Insured', 'PSIA 2001', 'Company Reg. 11756806'],
  boroughLinks:  [],
  faqs,
  cta: {
    primaryLabel: 'Get a security quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateServicePageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <ServicePage data={pageData} />
    </>
  )
}
