/**
 * BOROUGH PAGE — Southwark
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:51:01
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172932/vigil/security/service/security-guard-event-service-security-london.webp",
    alt:    "Security team in branded jackets providing manned guarding on a London street",
    width:  7500,
    height: 5000,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172932/vigil/security/service/security-guard-event-service-security-london.webp",
    alt:    "Security team in branded jackets providing manned guarding on a London street",
    width:  7500,
    height: 5000,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Southwark?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and construction site security across all Southwark postcodes including SE1. Our SIA-licensed officers are deployed to corporate offices around London Bridge, Borough, and Bankside, construction sites across major regeneration projects including London Bridge Quarter and Elephant & Castle, retail premises and hospitality venues, cultural institutions including Tate Modern and Shakespeare\'s Globe, healthcare facilities, and residential developments. All officers are directly employed by Vigil, DBS-checked, and trained in access control, incident response, conflict management, and first aid. We provide both scheduled contracts and emergency callouts with 24/7 availability.'
  },
  {
    question: 'Do you provide construction site security in Southwark?',
    answer: 'Yes. Southwark is experiencing extensive construction activity including major office developments around London Bridge and Bankside, residential regeneration projects in Elephant & Castle and Old Kent Road, mixed-use developments across Borough and Bermondsey, and infrastructure projects including London Bridge station upgrades and Thameslink works. Vigil provides specialist construction site security including 24/7 gatehouse manned by SIA-licensed officers trained in CDM 2015 protocols, mobile patrols for unstaffed hours with GPS-tracked site perimeters, tool audits verifying all plant and equipment, PPE enforcement, visitor sign-in and contractor verification, and alarm response for perimeter detection systems. Officers understand construction site hazards, welfare obligations, and project timeline pressures. We serve main contractors, developers, and project managers operating across Southwark from small infill sites to major mixed-use schemes.'
  },
  {
    question: 'What areas of Southwark do you cover?',
    answer: 'Vigil Security covers all Southwark postcodes including SE1 and surrounding areas. We deploy officers to commercial zones such as London Bridge and More London corporate offices, Borough and Bankside hospitality and cultural institutions, Elephant & Castle and Old Kent Road regeneration zones, Bermondsey warehouse conversions and residential developments, and Waterloo corporate and transport hub areas. Southwark spans from the Thames riverside through to Dulwich and Peckham, and our officers are familiar with its diverse commercial landscape including corporate finance, hospitality, construction, cultural institutions, and residential sectors. We also serve multiple sites across Southwark and neighbouring boroughs under consolidated contracts.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Southwark | B2B Contracts | Vigil',
    description:  'Commercial security Southwark. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-southwark/',
    focusKeyword: 'commercial security southwark',
  },
  borough:      'Southwark',
  region:       'South London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Southwark. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Southwark. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Southwark is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Southwark', description: 'Scheduled security for Southwark offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Southwark.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Southwark contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Southwark quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
