/**
 * SERVICE PAGE — Mobile Patrol Security London
 * Template: ServicePage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }  from 'next'
import ServicePage    from '@/components/templates/ServicePage'
import { generateServicePageSchema } from '@/lib/schema/service-page-schema'
import type { ServicePageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:51:10
// Manage at: app.vigilservices.co.uk/admin/pages
const images: ServicePageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
    priority: true,
  },
  intro: {
    src:    "/placeholder-image.svg",
    alt:    "Intro image — assign via CRM",
    width:  600,
    height: 400,
  },
  step1: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 1 — assign via CRM",
    width:  400,
    height: 300,
  },
  step2: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 2 — assign via CRM",
    width:  400,
    height: 300,
  },
  step3: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 3 — assign via CRM",
    width:  400,
    height: 300,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  caseStudy: {
    src:    "/placeholder-image.svg",
    alt:    "Case study image — assign via CRM",
    width:  800,
    height: 450,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What is a mobile patrol security service?',
    answer: 'Mobile patrol security involves SIA-licensed officers conducting scheduled visits to your premises at agreed intervals throughout the day or night. Officers arrive in a marked Vigil vehicle, complete external and internal checks of your site, test door locks and window security, check alarm systems, inspect perimeters and car parks, and produce a timestamped patrol report. Visits typically last 15-30 minutes and occur 2-4 times per shift. Mobile patrols provide visible deterrence at a lower cost than static manned guarding, making them ideal for sites that do not require continuous on-site presence but benefit from regular security checks.'
  },
  {
    question: 'How often will you visit our premises?',
    answer: 'Visit frequency is tailored to your risk profile and budget. Standard configurations include 2 visits per night (e.g., 22:00 and 03:00), 3 visits per night (e.g., 21:00, 00:00, 04:00), 4 visits per shift for higher-risk sites, or daytime-only visits for retail or office premises requiring perimeter checks during trading hours. We can also provide ad-hoc patrols for weekends, bank holidays, or during your closure periods. Visit times are randomised within agreed windows to prevent predictability.'
  },
  {
    question: 'What areas do mobile patrols cover during each visit?',
    answer: 'Officers follow a site-specific patrol route covering all agreed checkpoints. Typical checks include testing all external doors and gates for security, inspecting windows for damage or forced entry, walking the site perimeter and boundary fencing, checking car parks and loading bays for unauthorised vehicles or persons, inspecting external lighting and CCTV cameras, confirming alarm systems are set correctly, and noting any maintenance issues or hazards. Officers use our digital patrol system to scan NFC checkpoints at each location, providing auditable proof that all areas were inspected. If any issues are identified — such as a door left insecure or suspicious activity — we escalate immediately via phone and include detailed notes and photographs in the patrol report.'
  },
  {
    question: 'Can mobile patrols respond to our alarm activations?',
    answer: 'Yes. Mobile patrol officers can respond to intruder alarms, fire alarms, or panic alarms at your site. If your monitoring station or alarm company detects an activation, they contact our 24/7 control room. We dispatch the nearest available officer to your premises promptly in line with your agreed service level. The officer attends, investigates the cause, secures the premises if necessary, liaises with police or fire services if required, and produces a detailed incident report. Many clients combine mobile patrols with our dedicated key holding and alarm response service for faster callouts and keyholder access. See our Key Holding & Alarm Response page for full details.'
  },
  {
    question: 'Are mobile patrols suitable for construction sites?',
    answer: 'Mobile patrols are widely used for construction sites, particularly during non-working hours. Officers check site boundaries and hoarding, inspect gates and padlocks, confirm plant machinery and tools are secured, check welfare units and site offices for forced entry, and report any signs of trespass or theft. For high-value sites or those with significant theft risk, we often recommend combining mobile patrols with static manned guarding during high-risk periods. All officers assigned to construction sites are briefed on CDM 2015 site safety requirements and wear appropriate PPE during patrols.'
  },
  {
    question: 'How do we receive patrol reports?',
    answer: 'Every patrol visit generates an automated report uploaded to our client portal within 30 minutes of completion. Reports include visit date and time, officer name and SIA licence number, all checkpoints scanned with GPS timestamps, observations and issues identified, photographs of any defects or concerns, and confirmation that the site was left secure. You can log into the portal at any time to review historical reports or set up email alerts for new reports. If an urgent issue is identified during a patrol — such as a door left insecure or suspicious activity — the officer will also call you directly before leaving site.'
  }
]

const pageData: ServicePageData = {
  seo: {
    title:        'Mobile Patrols London | Mobile Patrol Security Services',
    description:  'mobile patrol security London — SIA-licensed mobile patrol officers across Greater London. Cost-effective security patrols for offices, retail, and industrial premises. Directly employed, £10M insured.',
    canonical:    'https://security.vigilservices.co.uk/mobile-patrols-london/',
    focusKeyword: 'mobile patrol security london',
  },
  h1:          'Mobile Patrol Security London',
  subheadline: 'SIA licensed. BS7858 vetted. 15-minute response. Greater London.',
  quickAnswer: 'Vigil Security Services provides mobile patrol security london exclusively to businesses across Greater London. Every officer is directly employed — never agency supplied.',
  intro:       '<p>Vigil Security Services works exclusively with businesses across Greater London. Every officer is directly employed by Vigil Services Ltd — SIA-licensed, BS7858 vetted, and consistently assigned to your contract.</p>',
  services:    [],
  processSteps: [
    { number: 1, title: 'Contact Vigil',
       description: 'Call or complete the enquiry form. We respond within 15 minutes.',
       timeframe: 'Within 15 minutes' },
    { number: 2, title: 'Site risk assessment',
       description: 'We visit your premises, assess your security requirements, and produce a written specification.',
       timeframe: 'Within 48 hours' },
    { number: 3, title: 'Officers deployed',
       description: 'Your directly employed, SIA-licensed team begins on your agreed start date.',
       timeframe: 'As agreed' },
  ],
  eeatPoints:    [
    { icon: '🪪', title: 'SIA-licensed officers', description: 'Every officer holds a current SIA licence in the appropriate category — Security Guarding or Door Supervision.' },
    { icon: '🔒', title: 'BS7858 vetted', description: 'Full 5-year employment history check and ID verification before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital shift reports', description: 'Timestamped shift logs and incident reports after every deployment.' },
  ],
  complianceTags: ['SIA Licensed', 'BS7858 Vetted', 'DBS Enhanced', 'Directly Employed',
                   '£10M Insured', 'PSIA 2001', 'Company Reg. 11756806'],
  boroughLinks:  [],
  faqs,
  cta: {
    primaryLabel: 'Get a security quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateServicePageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <ServicePage data={pageData} />
    </>
  )
}
