/**
 * VIGIL PAGE TEMPLATE TYPE DEFINITIONS
 * Version: 1.0 — June 2026
 *
 * This file is the structural contract for all Vigil page templates.
 * Every template component (ServicePage, BoroughPage, BlogPost,
 * LocationHub) accepts data conforming to these interfaces.
 *
 * The CRM Page Manager generates data blocks that satisfy these types.
 * Never change a field name without updating the CRM Page Manager.
 *
 * CRITICAL RULES:
 * - images block is always defined at the top of page files
 * - og image inherits hero if not separately defined
 * - All CTAs point to CRM enquiry URLs only
 * - Canonical always absolute with trailing slash
 * - focusKeyword appears in H1, meta title, first paragraph
 */

// ─────────────────────────────────────────────────────────────────────────────
// PRIMITIVES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single image slot — the atomic unit of image management.
 * Every image in every template is expressed as an ImageSlot.
 * The CRM DAM generates these from Cloudinary URLs + AI alt text.
 */
export interface ImageSlot {
  src:       string   // Cloudinary URL or local storage URL
  alt:       string   // AI-generated or manually set — never empty
  width:     number   // Exact pixel width for Next.js Image
  height:    number   // Exact pixel height for Next.js Image
  priority?: boolean  // true on hero images only — above fold
  caption?:  string   // Optional visible caption below image
}

/**
 * All image slots for a page.
 * Only hero and og are required on every page.
 * Missing optional slots render a placeholder or are hidden.
 * og inherits hero src/alt/width/height if not separately defined.
 */
export interface ImageSlots {
  hero:       ImageSlot          // Required. 1200×630. priority=true
  intro?:     ImageSlot          // 600×400. Beside intro text
  step1?:     ImageSlot          // 400×300. Process step 1
  step2?:     ImageSlot          // 400×300. Process step 2
  step3?:     ImageSlot          // 400×300. Process step 3
  trust?:     ImageSlot          // 500×500. Square. Team/EEAT section
  caseStudy?: ImageSlot          // 800×450. Case study section
  og:         ImageSlot          // 1200×630. Social sharing metadata
}

/** Borough-specific image slots — fewer, simpler */
export interface BoroughImageSlots {
  hero:    ImageSlot   // 1200×630. Local landmark preferred
  service: ImageSlot   // 600×400. Service in action
  local?:  ImageSlot   // 600×400. Area-specific context
  trust?:  ImageSlot   // 500×500. Team or staff photo
  og:      ImageSlot   // 1200×630. Inherits hero if not set
}

/** Blog post image slots */
export interface BlogImageSlots {
  header:   ImageSlot   // 1200×628. Top of article. priority=true
  inline1?: ImageSlot   // 700×400. Mid-article
  inline2?: ImageSlot   // 700×400. Lower article
  og:       ImageSlot   // 1200×628. Inherits header if not set
}

// ─────────────────────────────────────────────────────────────────────────────
// SEO METADATA
// ─────────────────────────────────────────────────────────────────────────────

/**
 * SEO metadata required on every page.
 * Generated by the CRM and exported to Next.js metadata export.
 * Never change canonical without adding a 301 redirect first.
 */
export interface SEOMeta {
  title:        string   // 50-60 chars. Focus keyword first
  description:  string   // 145-155 chars. Keyword in first 60 chars
  canonical:    string   // Absolute URL. Trailing slash. Never changes
  focusKeyword: string   // Used in H1, title, first paragraph
  ogTitle?:     string   // Defaults to title if not set
  ogDescription?: string // Defaults to description if not set
  noIndex?:     boolean  // true only on admin/thank-you pages
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTENT COMPONENTS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * FAQ item — used in FAQPage schema and accordion component.
 * Question should be phrased as a real user question.
 * Answer: 40-60 words. Direct answer in first sentence.
 * Structured for featured snippets and voice search.
 */
export interface FAQ {
  question: string   // Natural language question
  answer:   string   // 40-60 words. Direct. UK English.
}

/**
 * Service card — used in services grid (6 cards per page)
 */
export interface ServiceCard {
  icon:        string   // Emoji or SVG string
  title:       string   // Service name
  description: string   // 1 sentence. B2B positioning
  href:        string   // Internal link to service page
  cta?:        string   // Optional card CTA label
}

/**
 * Process step — used in How It Works section (3 steps)
 */
export interface ProcessStep {
  number:      number
  title:       string
  description: string   // 2-3 sentences
  image?:      ImageSlot // step1/step2/step3 slot
  timeframe?:  string   // e.g. "Within 15 minutes"
}

/**
 * EEAT trust point — used in Why Vigil section (4 points)
 */
export interface TrustPoint {
  icon:        string   // Emoji or SVG
  title:       string   // Short label
  description: string   // 1-2 sentences. Evidence-based. No vague claims
  stat?:       string   // Optional verifiable statistic
}

/**
 * Case study — optional section on service pages
 * Keep anonymised until client permission obtained
 */
export interface CaseStudy {
  title:       string   // "How we..." or "[Sector] client case"
  challenge:   string   // What problem the client had
  solution:    string   // What Vigil did
  result:      string   // Measurable outcome
  sector:      string   // Industry sector for content matching
  borough?:    string   // Location for local SEO
  image?:      ImageSlot // caseStudy slot
  anonymous?:  boolean  // true = "A London facilities manager"
}

/**
 * CTA configuration — used throughout all templates
 * label varies by position. url is always CRM.
 */
export interface CTAConfig {
  primaryLabel:   string   // "Get a free quote"
  primaryUrl:     string   // CRM enquiry URL — never change
  phone:          string   // Division phone number
  phoneLabel?:    string   // "Call 020 3098 6037"
  secondaryLabel?: string  // "View all services"
  secondaryUrl?:  string   // Internal link
}

/**
 * Compliance tag — displayed in compliance strip
 */
export type ComplianceTag =
  | 'DBS Enhanced'
  | 'Directly Employed'
  | '£10M Insured'
  | 'COSHH Compliant'
  | 'AWR 2010'
  | 'CDM 2015'
  | 'TUPE 2006'
  | 'SIA Licensed'
  | 'BS7858 Vetted'
  | 'PSIA 2001'
  | 'Company Reg. 11756806'

/**
 * Related post — used at bottom of blog posts
 */
export interface RelatedPost {
  title: string
  href:  string
  date:  string
}

/**
 * Borough link — used in borough coverage grid
 */
export interface BoroughLink {
  name: string   // Display name e.g. "Westminster"
  href: string   // e.g. /commercial-cleaning-westminster/
  live: boolean  // false = coming soon (no link rendered)
}

// ─────────────────────────────────────────────────────────────────────────────
// PAGE DATA INTERFACES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ServicePageData — the complete data contract for service pages.
 *
 * Usage:
 * const pageData: ServicePageData = { ... }
 * export default function Page() {
 *   return <ServicePage data={pageData} />
 * }
 *
 * Image mapping:
 * The CRM Page Manager generates the `images` block.
 * All other fields are content — managed in the page file.
 */
export interface ServicePageData {
  // SEO layer
  seo:            SEOMeta

  // Hero section
  h1:             string    // Focus keyword in first 4 words
  subheadline:    string    // USP reinforcement — 1 sentence
  quickAnswer:    string    // AEO block — 2-3 sentences. Direct answer

  // Intro section
  intro:          string    // 2-3 paragraphs. B2B positioning. HTML ok

  // Services grid
  services:       ServiceCard[]   // Exactly 6 cards

  // Process section
  processSteps:   ProcessStep[]   // Exactly 3 steps

  // EEAT section
  eeatPoints:     TrustPoint[]    // Exactly 4 points
  eeatHeadline?:  string          // "Why London businesses choose Vigil"

  // Compliance
  complianceTags: ComplianceTag[] // 4-6 tags

  // Case study (optional)
  caseStudy?:     CaseStudy

  // Borough coverage
  boroughLinks:   BoroughLink[]   // All live borough pages for this division

  // FAQ
  faqs:           FAQ[]           // Minimum 5 questions

  // CTA
  cta:            CTAConfig

  // Images — generated by CRM Page Manager
  // All images defined here. Template reads from this block only.
  images:         ImageSlots

  // Schema — passed to JSON-LD script in metadata
  schema?: {
    serviceType: string
    areaServed:  string
  }
}

/**
 * BoroughPageData — data contract for borough/location pages.
 *
 * Simpler than ServicePage — fewer sections, local focus.
 * Borough agent generates these autonomously.
 */
export interface BoroughPageData {
  // SEO
  seo:            SEOMeta

  // Location context
  borough:        string    // "Westminster"
  region:         string    // "Central London"
  postcodes:      string[]  // ["SW1", "WC1", "W1"]

  // Content
  h1:             string    // "[Service] [Borough]" exact match
  quickAnswer:    string    // AEO block — borough-specific
  intro:          string    // 2 paragraphs. Borough-specific content
  localContext:   string    // Local landmarks, sectors, business types

  // Services (subset relevant to borough)
  services:       ServiceCard[]   // 4-6 cards

  // Local trust
  eeatPoints?:    TrustPoint[]    // Optional — 3 points

  // Nearby boroughs (internal linking)
  nearbyBoroughs: BoroughLink[]   // 3-5 adjacent boroughs

  // FAQ
  faqs:           FAQ[]           // Minimum 5 — borough-specific

  // CTA
  cta:            CTAConfig

  // Images — generated by CRM Page Manager + borough agent
  images:         BoroughImageSlots

  // Schema
  schema?: {
    borough:     string
    areaServed:  string[]
    serviceType: string
  }
}

/**
 * BlogPostData — data contract for blog posts.
 *
 * Content agent generates new posts conforming to this interface.
 */
export interface BlogPostData {
  // SEO
  seo:          SEOMeta

  // Post metadata
  h1:           string    // Question-format headline preferred
  published:    string    // ISO date string
  updated?:     string    // ISO date string — for freshness
  author:       string    // "Vigil Cleaning Services team"
  readTime?:    number    // Minutes

  // Content
  intro:        string    // 1 paragraph. Hook + quick answer
  body:         string    // Main content. HTML. Min 800 words
  conclusion:   string    // 1 paragraph. Soft CTA

  // Optional FAQ
  faqs?:        FAQ[]     // If present: FAQPage schema added

  // Related content
  relatedPosts: RelatedPost[]   // 2-3 related articles

  // CTA
  cta:          CTAConfig

  // Images
  images:       BlogImageSlots

  // Tags for content matching
  tags?:        string[]   // service types, sectors
}

/**
 * LocationHubData — hub page aggregating all borough pages.
 * /commercial-cleaning-london/ and /commercial-security-london/
 * One per site. Links to all borough pages.
 */
export interface LocationHubData {
  // SEO
  seo:          SEOMeta

  // Content
  h1:           string
  quickAnswer:  string
  intro:        string

  // All boroughs for this division — live and coming soon
  allBoroughs:  BoroughLink[]

  // Featured boroughs (high commercial value)
  featuredBoroughs: BoroughLink[]

  // Services overview
  services:     ServiceCard[]

  // FAQ
  faqs:         FAQ[]

  // CTA
  cta:          CTAConfig

  // Images
  images: {
    hero:   ImageSlot   // 1200×630
    og:     ImageSlot   // Inherits hero
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// CRM INTEGRATION TYPES
// These types are used by the CRM Page Manager
// to generate the images block for each page.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Page slot definition — stored in page_slot_templates table in CRM.
 * Defines what image slots a page type has.
 */
export interface PageSlotDefinition {
  slotKey:      keyof ImageSlots | keyof BoroughImageSlots | keyof BlogImageSlots
  label:        string
  purpose:      string
  width:        number
  height:       number
  aspectRatio:  string
  required:     boolean
  isPriority:   boolean  // Next.js priority prop
  isOg:         boolean  // Used in OG metadata
  inheritFrom?: string   // Slot key to inherit if empty
  imageType:    string   // Matches images.image_type in CRM
}

/**
 * Page image assignment — stored in page_image_assignments table.
 * Links a CRM image to a slot on a specific page.
 */
export interface PageImageAssignment {
  pageUrl:   string
  slotKey:   string
  imageId:   number    // CRM images.id
  imageSrc:  string    // Cloudinary URL
  imageAlt:  string    // From CRM AI Vision enrichment
  width:     number
  height:    number
  assignedAt: string
}

/**
 * Generated images block — output from CRM Page Manager.
 * Paste this const block at the top of any page file.
 * Replace the existing images const to update all images.
 */
export interface GeneratedImagesBlock {
  pageUrl:      string
  pageType:     'service' | 'borough' | 'blog' | 'hub'
  generatedAt:  string
  slots:        Partial<ImageSlots & BoroughImageSlots & BlogImageSlots>
  // The const block to paste into the page file:
  codeBlock:    string
}
