/**
 * BLOG POST — Licensing Act 2003 Security
 * Template: BlogPost v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }  from 'next'
import BlogPost       from '@/components/templates/BlogPost'
import { generateBlogPostSchema } from '@/lib/schema/blog-post-schema'
import type { BlogPostData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:50:50
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BlogPostData["images"] = {
  header: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172878/vigil/security/service/construction-site-security-london-vigil-security-services-security-london.webp",
    alt:    "Vigil security officer in hi-vis jacket with SIA licence and CSCS hard hat using handheld device at London construction site",
    width:  1234,
    height: 864,
    priority: true,
  },
  inline1: {
    src:    "/placeholder-image.svg",
    alt:    "Inline image 1 — assign via CRM",
    width:  700,
    height: 400,
  },
  inline2: {
    src:    "/placeholder-image.svg",
    alt:    "Inline image 2 — assign via CRM",
    width:  700,
    height: 400,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172878/vigil/security/service/construction-site-security-london-vigil-security-services-security-london.webp",
    alt:    "Vigil security officer in hi-vis jacket with SIA licence and CSCS hard hat using handheld device at London construction site",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What is the Licensing Act 2003 and who does it apply to?',
    answer: "The Licensing Act 2003 is the primary legislation governing the sale of alcohol, provision of regulated entertainment, and sale of hot food and drink late at night in England and Wales. It applies to any business that sells alcohol, provides regulated entertainment (such as live music, DJ sets, or films), or sells hot food or drink between 11pm and 5am — including pubs, bars, nightclubs, restaurants, off-licences, hotels, and members' clubs. Premises must hold a premises licence or a temporary event notice (TEN) to carry out these licensable activities. Security requirements are often imposed as conditions on the licence to ensure the four licensing objectives are met: prevention of crime and disorder, public safety, prevention of public nuisance, and protection of children from harm.",
  },
  {
    question: 'When is door supervision required under the Licensing Act?',
    answer: 'Door supervision is not automatically required for all licensed premises — it is imposed as a condition on the premises licence where the licensing authority believes it is necessary to promote the licensing objectives, particularly the prevention of crime and disorder and public safety. Conditions requiring door supervision are most commonly imposed on late-night venues such as nightclubs, large pubs, and bars that operate beyond midnight or have a history of disorder. The specific requirement will be set out in the premises licence and may specify the number of door supervisors required, the hours they must be on duty, and the areas they must cover. Failure to comply with a door supervision condition is a criminal offence.',
  },
  {
    question: 'Do door supervisors need to be SIA licensed?',
    answer: 'Yes, in almost all cases. Under the Private Security Industry Act 2001, anyone who carries out door supervision activities for payment must hold a valid SIA Door Supervision licence. The SIA licence confirms that the individual has completed approved training covering conflict management, physical intervention, health and safety, and the legal framework, and has undergone a DBS criminal record check. The licence must be current and displayed visibly at all times. Using unlicensed door supervisors is a criminal offence and can also result in a licence review under the Licensing Act, potentially leading to additional conditions, suspension, or revocation of the premises licence.',
  },
  {
    question: 'What security-related conditions can be imposed on a premises licence?',
    answer: 'Common security-related conditions include: door supervision requirements (specifying number of SIA-licensed supervisors, hours, and areas); CCTV requirements (installation and maintenance covering entry/exit points and key areas, footage retained typically 28-31 days and available to police on request); incident logs (written record of all incidents of crime, disorder, refusals of service, and ejections); capacity limits (maximum number of patrons, often monitored by door supervisors); ID scanning or entry policies; and staff training requirements. Conditions can also address plastic or toughened glass, control of external areas, dispersal policies, and liaison with police and local authorities.',
  },
  {
    question: 'What happens if a premises licence condition is breached?',
    answer: "Breaching a premises licence condition is a criminal offence under the Licensing Act 2003. The licence holder and the designated premises supervisor can be prosecuted and, if convicted, face a fine of up to £20,000 and/or up to six months' imprisonment. A breach can also trigger a licence review — the police, licensing authority, or local residents can apply to the licensing authority to review the licence. Following a review hearing, the licensing authority can modify conditions, suspend the licence for up to three months, or revoke the licence entirely. Revocation means the premises can no longer operate as a licensed venue.",
  },
  {
    question: 'How can I find out what conditions are on my premises licence?',
    answer: "Your premises licence is a legal document issued by the licensing authority. It consists of two parts: the premises licence itself (including licensable activities, hours, and conditions), and the licence summary (which must be displayed prominently at the premises). The full premises licence includes an annexe setting out all conditions — those proposed in your operating schedule, those imposed following a hearing, and those agreed with the police. If you have lost your copy, request a certified copy from the licensing authority. If unsure what a condition means or how to comply, contact the licensing authority or seek professional advice — ignorance of conditions is not a defence.",
  },
]

const postData: BlogPostData = {
  seo: {
    title:        'Licensing Act 2003: Security for London Venues | Vigil',
    description:  'Complete guide to security requirements under the Licensing Act 2003 for pubs, clubs, and licensed premises in London. Understand your legal obligations and conditions.',
    canonical:    'https://security.vigilservices.co.uk/blog/licensing-act-2003-security',
    focusKeyword: 'Licensing Act 2003 security London venues',
  },

  h1:        'Licensing Act 2003 — Security Obligations for London Licensed Premises',
  published: '2026-06-02',
  author:    'Vigil Security Services team',
  readTime:  12,

  intro: '<p>If you operate a pub, club, or licensed premises in London, the Licensing Act 2003 governs your security obligations. Security requirements — door supervision, CCTV, incident logs — are imposed as licence conditions to promote crime prevention and public safety. All door supervisors must hold a current SIA Door Supervision licence. This guide explains when door supervision is required, what conditions mean in practice, and the consequences of non-compliance.</p>',

  body: `
<h2>Understanding the Licensing Act 2003</h2>
<p>The Licensing Act 2003 is the cornerstone of licensing law in England and Wales. It replaced the previous patchwork of licensing legislation with a single, unified regime for regulating the sale of alcohol, the provision of regulated entertainment (such as live music, DJ sets, dance performances, and film exhibitions), and the sale of hot food and drink late at night (between 11pm and 5am). Any business that engages in these licensable activities must hold either a premises licence or a temporary event notice (TEN) granted by the local licensing authority, which is typically the local council.</p>
<p>The Act is underpinned by four licensing objectives: the prevention of crime and disorder, public safety, the prevention of public nuisance, and the protection of children from harm. All licence conditions must be appropriate, proportionate, and necessary to achieve these objectives. Security requirements — such as door supervision, CCTV, incident logs, and capacity controls — are among the most common conditions imposed on licences, particularly for late-night venues in urban areas like London where the risks of crime, disorder, and public nuisance are higher.</p>
<p>For businesses operating licensed premises in London, understanding and complying with the Licensing Act is not just a legal obligation — it is essential to maintaining good relations with the local community, police, and licensing authority. Breaches of licence conditions can lead to prosecution, fines, licence reviews, and ultimately revocation of the licence, which would force the business to cease trading.</p>

<h2>When Is Door Supervision Required?</h2>
<p>Door supervision is not a blanket requirement for all licensed premises. Instead, it is imposed as a condition on the premises licence where the licensing authority believes it is necessary to promote the licensing objectives, particularly the prevention of crime and disorder and public safety. The decision to impose door supervision conditions is made on a case-by-case basis, taking into account factors such as the nature of the premises, the hours of operation, the clientele, the location, and any history of incidents or complaints.</p>
<p>Door supervision conditions are most commonly imposed on late-night venues such as nightclubs, large pubs, and bars that operate beyond midnight. They are also commonly required for venues that have experienced problems with violence, disorder, drug use, or public nuisance complaints from residents. In some cases, door supervision may be required only on certain nights of the week (such as Friday and Saturday nights) or during certain hours (such as after 10pm). The specific requirement will be set out in the annexe to your premises licence.</p>
<p>Even if door supervision is not a formal condition on your licence, employing security can be a sensible and responsible choice. Door supervisors can manage entry and exit, prevent overcrowding, check IDs to prevent underage drinking, deter troublemakers, respond to incidents, and assist with the safe dispersal of patrons at closing time. By demonstrating that you are taking the licensing objectives seriously, you can build a positive relationship with the police and licensing authority, reduce the risk of complaints and licence reviews, and create a safer environment for your customers.</p>

<h2>SIA Licensing Requirements for Door Supervisors</h2>
<p>Under the Private Security Industry Act 2001, anyone who carries out door supervision activities for payment must hold a valid SIA Door Supervision licence. Door supervision is defined as guarding premises against unauthorised access or occupation, against outbreaks of disorder, or against damage. In the context of licensed premises, this includes controlling entry, checking IDs, managing queues, ejecting individuals who are behaving inappropriately, and monitoring behaviour inside the venue to prevent disorder.</p>
<p>The SIA Door Supervision licence confirms that the individual has completed an SIA-approved training course covering conflict management, physical intervention, health and safety, and the legal framework governing security work. It also confirms that the individual has undergone a Disclosure and Barring Service (DBS) criminal record check and has been assessed by the SIA as suitable for working in a position of trust. The licence is valid for three years and must be renewed before it expires, with a fresh DBS check required at renewal.</p>
<p>Licensing authorities routinely specify in licence conditions that all door supervisors must be SIA licensed, and the licence must be displayed visibly at all times when the individual is working. Police and council officers have the power to visit licensed premises and inspect door supervisors' licences. If an unlicensed individual is found working as a door supervisor, both the individual and the premises can face prosecution under the Private Security Industry Act. The use of unlicensed door staff can also trigger a licence review under the Licensing Act, as it demonstrates a failure to comply with licence conditions and a disregard for the licensing objectives.</p>

<h2>Common Security-Related Licence Conditions</h2>
<p>Premises licences can include a wide range of security-related conditions, tailored to the specific risks and characteristics of the venue. Door supervision conditions typically specify the number of SIA-licensed door supervisors required, the hours they must be on duty, and the areas they must cover (such as entry and exit points, the bar, the dance floor, or external smoking areas). Some conditions also specify the ratio of male to female door supervisors, or require that supervisors wear high-visibility clothing or ID badges.</p>
<p>CCTV conditions are also very common. These typically require the installation and maintenance of a CCTV system covering all entry and exit points, the bar, the till area, and other key locations. The system must record continuously during opening hours, and footage must be retained for a minimum period (usually 28 or 31 days) and made available to police or licensing officers on request. Some conditions also require that CCTV images be of sufficient quality to identify individuals, that the system be regularly maintained and serviced, and that staff be trained in its operation.</p>
<p>Incident log conditions require the premises to maintain a written record of all incidents of crime, disorder, refusals of service, and ejections. The log must include the date and time, a description of what happened, the names of those involved where known, and the action taken. The log must be kept on the premises and made available to police and licensing officers on request.</p>
<p>Other common conditions include capacity limits (restricting the maximum number of patrons, often monitored using clicker counters); ID scanning or entry policies; training requirements (requiring staff to be trained in conflict management, age verification, and the Licensing Act); and use of plastic or toughened glassware (to reduce injury risk in the event of a fight or accident).</p>

<h2>Consequences of Breaching Licence Conditions</h2>
<p>Breaching a premises licence condition is a criminal offence under Section 136 of the Licensing Act 2003. The premises licence holder and, where applicable, the designated premises supervisor can be prosecuted. On conviction, they face a fine of up to £20,000 and/or up to six months' imprisonment. For serious or repeated breaches, the penalties can be significant, and a criminal conviction can have long-term consequences for individuals and businesses.</p>
<p>In addition to criminal prosecution, a breach of licence conditions can trigger a licence review. The police, the licensing authority, local residents, or other interested parties can apply to the licensing authority to review the premises licence, presenting evidence of the breach and arguing that the licensing objectives are being undermined. Following a review hearing, the licensing authority can take a range of actions, including: modifying the conditions of the licence; excluding certain licensable activities; removing the designated premises supervisor; suspending the licence for up to three months; or revoking the licence entirely.</p>
<p>A licence review is a serious matter with potentially catastrophic consequences for the business. Revocation of the licence means the premises can no longer operate as a licensed venue. Even if the licence is not revoked, the imposition of additional conditions or a suspension can have significant financial and reputational impacts. Compliance with licence conditions must therefore be a top priority, and businesses should have robust systems in place to monitor and document compliance.</p>

<h2>How to Stay Compliant</h2>
<p>Staying compliant with your premises licence conditions requires ongoing vigilance and good management practices. First, ensure that you have a copy of your full premises licence and that you and your staff are familiar with all the conditions. The licence summary must be displayed prominently at the premises so that it is visible to customers and enforcement officers. Review the conditions regularly, particularly if you are considering changes to your operating hours, activities, or layout.</p>
<p>If your licence requires door supervision, ensure that you always have the required number of SIA-licensed door supervisors on duty during the specified hours. Verify their licences on the <a href="https://www.sia.homeoffice.gov.uk" target="_blank" rel="noopener noreferrer">SIA public register</a> before they begin work, and keep copies of their licences on file. Monitor licence expiry dates and ensure that supervisors renew their licences in good time. Do not rely solely on the supervisor to manage this — take responsibility for checking compliance yourself.</p>
<p>If your licence requires CCTV, ensure that the system is working properly, that footage is being recorded continuously, and that footage is retained for the required period. Conduct regular checks and maintenance, and keep records of when maintenance was carried out. Train your staff in how to operate the system and how to provide footage to police or licensing officers on request.</p>
<p>Finally, build a positive relationship with your local police licensing team and licensing authority. Respond promptly to any concerns they raise, cooperate with visits and inspections, and demonstrate that you are committed to operating responsibly and promoting the licensing objectives. A good relationship can help you resolve issues informally, avoid formal enforcement action, and build trust that will stand you in good stead if problems do arise.</p>

<div style="margin-top:2rem;padding:1.25rem;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:0.75rem">
<p style="font-size:0.75rem;text-transform:uppercase;letter-spacing:0.1em;color:rgba(255,255,255,0.4);margin-bottom:0.75rem">External references</p>
<ul style="list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:0.5rem">
<li><a href="https://www.gov.uk/guidance/alcohol-licensing" target="_blank" rel="noopener noreferrer">GOV.UK Alcohol Licensing Guidance — official guidance on the Licensing Act 2003 and licensing procedures</a></li>
<li><a href="https://www.legislation.gov.uk/ukpga/2003/17/contents" target="_blank" rel="noopener noreferrer">Licensing Act 2003 (Full Text) — the complete legislation as published on legislation.gov.uk</a></li>
<li><a href="https://www.gov.uk/government/publications/explanatory-memorandum-revised-guidance-issued-under-s-182-of-licensing-act-2003" target="_blank" rel="noopener noreferrer">Section 182 Guidance (Home Office) — statutory guidance to licensing authorities on the Licensing Act 2003</a></li>
</ul>
</div>
`,

  conclusion: '<p>Published 2 June 2026 · Vigil Services Ltd · Ferguson House, 113 Cranbrook Road, Ilford IG1 4PU · SIA licensed · Directly employed officers · PSIA 2001 compliant</p>',

  faqs,

  relatedPosts: [
    {
      title: 'SIA licensing explained — what to check before hiring a security company',
      href:  '/blog/sia-licensing-explained/',
      date:  '2026-06-02',
    },
    {
      title: 'BS7858 vetting explained: why it matters for your business',
      href:  '/blog/bs7858-vetting-explained/',
      date:  '2026-06-02',
    },
  ],

  cta: {
    primaryLabel: 'Book SIA-licensed door supervisors',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },

  images,

  tags: ['Licensing Act 2003', 'door supervision', 'SIA licensing', 'licensed premises', 'London venues'],
}

export const metadata: Metadata = {
  title:       postData.seo.title,
  description: postData.seo.description,
  alternates:  { canonical: postData.seo.canonical },
  openGraph: {
    title:       postData.seo.title,
    description: postData.seo.description,
    url:         postData.seo.canonical,
    locale:      'en_GB',
    type:        'article',
    publishedTime: postData.published,
    images: [{
      url:    images.og.src,
      width:  images.og.width,
      height: images.og.height,
      alt:    images.og.alt,
    }],
  },
  other: {
    'article:published_time': postData.published,
    'article:modified_time':  postData.published,
  },
}

export default function Page() {
  const schema = generateBlogPostSchema(postData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BlogPost data={postData} division="security" />
    </>
  )
}
