/**
 * BOROUGH PAGE — Islington
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:42:48
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172932/vigil/security/service/security-guard-event-service-security-london.webp",
    alt:    "Security team in branded jackets providing manned guarding on a London street",
    width:  7500,
    height: 5000,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172932/vigil/security/service/security-guard-event-service-security-london.webp",
    alt:    "Security team in branded jackets providing manned guarding on a London street",
    width:  7500,
    height: 5000,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Islington?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and concierge services across all Islington postcodes including N1, EC1, N5. Our SIA-licensed officers are deployed to corporate offices in Angel and Old Street, tech startups around Silicon Roundabout, retail premises along Upper Street and Chapel Market, construction sites, healthcare facilities, educational institutions, and residential developments. All officers are directly employed by Vigil, DBS-checked, and trained in access control, incident response, conflict management, and first aid. We provide both scheduled contracts and emergency callouts with 24/7 availability across Islington\'s commercial zones.'
  },
  {
    question: 'Are your Islington security officers SIA-licensed?',
    answer: 'Yes. Every officer deployed to Islington holds a current SIA licence in the appropriate category — Security Guarding, Door Supervision, or CCTV Operations. The Security Industry Authority regulates private security in the UK and mandates licensing for all frontline officers. All licences are verified at recruitment and renewed every three years. We do not use agency staff or sub-contractors. Every guard assigned to an Islington contract is directly employed by Vigil, ensuring accountability, consistency, and adherence to our service standards. Officers deployed to Islington are familiar with the borough\'s mix of corporate offices, tech startups, retail, and hospitality sectors, and understand the security requirements specific to central London commercial environments.'
  },
  {
    question: 'How quickly can you mobilise security services in Islington?',
    answer: 'For standard manned guarding or mobile patrol contracts in Islington, we typically mobilise within 48–72 hours of contract signature. This includes conducting a site risk assessment, assigning officers, completing site-specific training, and issuing uniforms and equipment. For emergency deployments — such as following a break-in, vandalism incident, or sudden staff absence — we maintain a pool of trained relief officers and can often deploy to Islington sites within 24 hours. For key holding and alarm response services, we can usually activate your account within 24 hours once we hold your site keys and alarm codes. Islington\'s central location and high density of commercial premises mean we prioritise rapid response times to N1, EC1, N5 addresses during emergencies.'
  },
  {
    question: 'What areas of Islington do you cover?',
    answer: 'Vigil Security covers all Islington postcodes including N1, EC1, N5 and surrounding areas. We deploy officers to commercial zones such as Angel and Upper Street corporate offices and retail, Old Street and Silicon Roundabout tech startups and co-working spaces, Clerkenwell creative agencies and offices, Highbury and Holloway residential and mixed-use developments, Archway and Tufnell Park town centres, and King\'s Cross regeneration zone offices and construction sites. Islington is one of central London\'s most commercially diverse boroughs, and our officers are familiar with its office districts, retail corridors, hospitality zones, and construction activity. We also serve multiple sites across Islington and neighbouring boroughs under consolidated contracts for clients with London-wide operations.'
  },
  {
    question: 'Do you provide security for Islington corporate offices and tech startups?',
    answer: 'Yes. Islington is home to a significant concentration of corporate offices, particularly around Angel and Clerkenwell, and a thriving tech startup sector centred on Old Street Silicon Roundabout. These environments require professional security including access control, visitor management, CCTV monitoring, and incident response. Vigil provides manned guarding for office reception and gatehouse duties, mobile patrols for overnight and weekend periods when offices are unoccupied, key holding and alarm response for out-of-hours incidents, and CCTV monitoring services. Officers assigned to Islington corporate and tech clients are trained to provide professional security that integrates with office operations without disrupting business activity or creating barriers to legitimate visitors and staff.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Islington | B2B Contracts | Vigil',
    description:  'Commercial security Islington. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-islington/',
    focusKeyword: 'commercial security islington',
  },
  borough:      'Islington',
  region:       'North London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Islington. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Islington. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Islington is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Islington', description: 'Scheduled security for Islington offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Islington.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Islington contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Islington quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
