/**
 * SERVICE PAGE — Door Supervisors London
 * Template: ServicePage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }  from 'next'
import ServicePage    from '@/components/templates/ServicePage'
import { generateServicePageSchema } from '@/lib/schema/service-page-schema'
import type { ServicePageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:51:06
// Manage at: app.vigilservices.co.uk/admin/pages
const images: ServicePageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
    priority: true,
  },
  intro: {
    src:    "/placeholder-image.svg",
    alt:    "Intro image — assign via CRM",
    width:  600,
    height: 400,
  },
  step1: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 1 — assign via CRM",
    width:  400,
    height: 300,
  },
  step2: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 2 — assign via CRM",
    width:  400,
    height: 300,
  },
  step3: {
    src:    "/placeholder-image.svg",
    alt:    "Process step 3 — assign via CRM",
    width:  400,
    height: 300,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  caseStudy: {
    src:    "/placeholder-image.svg",
    alt:    "Case study image — assign via CRM",
    width:  800,
    height: 450,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782173012/vigil/security/service/sia-security-guard-london-vigil-security-services-security-london.webp",
    alt:    "Uniformed Vigil Security Services officer with SIA licence on duty in the City of London near the Gherkin",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'Is a door supervisor licence a legal requirement for licensed premises?',
    answer: 'Yes. Under the Private Security Industry Act 2001, any individual working as a door supervisor at licensed premises must hold a current SIA Door Supervisor licence. This applies to all venues licensed under the Licensing Act 2003 to sell or supply alcohol — including pubs, bars, nightclubs, restaurants with late licences, and event venues. Deploying unlicensed individuals in a door supervisor role is a criminal offence for both the individual and the employer, and can result in prosecution, fines, and the revocation of the premises licence. Many venue licences also contain conditions specifying minimum numbers of licensed door supervisors required during operating hours or at specific event types. Vigil only deploys SIA-licensed door supervisors, and all licences are verified at recruitment and monitored for expiry. Clients can request sight of any officer\'s SIA licence badge upon arrival at the venue.'
  },
  {
    question: 'What do door supervisors do at licensed premises?',
    answer: 'Door supervisors are responsible for managing safe, orderly entry and exit at licensed premises, including pubs, bars, nightclubs, restaurants, and event venues. Their duties include verifying that patrons meet the venue\'s entry requirements (age verification using ID checks, dress code compliance, sobriety assessment), managing queues outside the venue to maintain public order, refusing entry to individuals who are intoxicated, aggressive, or failing to meet entry criteria, conducting searches of bags and clothing where permitted under the venue\'s conditions, monitoring crowd density inside the venue to prevent dangerous overcrowding, managing and documenting ejections of patrons who breach venue rules, de-escalating conflicts between patrons before they escalate to physical confrontations, liaising with police when incidents require law enforcement involvement, and completing incident logs and CCTV evidence records. Door supervisors also play a welfare role — identifying and assisting patrons who appear vulnerable, distressed, or in need of medical attention, and contacting emergency services if required.'
  },
  {
    question: 'How many door supervisors do we need for our venue?',
    answer: 'The number of door supervisors required depends on your venue\'s licence conditions, operating capacity, event type, and risk profile. Many premises licences specify minimum staffing ratios — for example, 1 door supervisor per 100 patrons, or 1 door supervisor at each entry and exit point. Where your licence does not specify ratios, industry guidance and best practice suggest: small venues (up to 100 capacity) typically require 2 door supervisors; medium venues (100–300 capacity) require 3–5; large venues (300–500 capacity) require 6–8; and high-capacity nightclubs or events require proportional scaling. High-risk venues — those with a history of incidents, late-night operating hours, or large outdoor areas — may require additional officers. We recommend discussing your specific venue with us so we can advise based on your licence conditions, operating hours, event schedule, and risk assessment. For venues operating regular late-night licences, we can provide a fixed rota of allocated officers to ensure consistency and familiarity with your premises.'
  },
  {
    question: 'Can Vigil provide door supervisors at short notice?',
    answer: 'Yes. Vigil maintains a pool of trained, SIA-licensed door supervisors available for short-notice deployments across Greater London. For regular shifts at established venues (pubs, bars, nightclubs), we can typically mobilise cover within 24–48 hours of a request. For emergency situations — for example, a sudden shortage due to staff illness or a last-minute licence condition requirement — we aim to source and deploy cover within 12–24 hours where operationally feasible. However, we strongly recommend establishing an ongoing contract for regular venues rather than relying on ad-hoc bookings. A contract arrangement ensures you have guaranteed officer allocation, consistent staffing (the same officers familiar with your premises and regulars), and priority access to cover during busy periods such as Bank Holidays, New Year\'s Eve, and major sporting events when demand for licensed security is highest. Contact us to discuss whether a contract or flexible arrangement is appropriate for your venue.'
  },
  {
    question: 'What is the difference between a door supervisor and a security guard?',
    answer: 'In UK law, door supervisors and security guards hold different SIA licences and are authorised to carry out different roles. An SIA Door Supervisor licence authorises the holder to work as a door supervisor at licensed premises, to use physical intervention if necessary (including restraint and ejection), and to conduct searches of individuals. An SIA Security Guard licence authorises the holder to work as a static or mobile security officer — for example, guarding a retail premises, an office building, or a construction site — but does not authorise the holder to work as a door supervisor at licensed premises, and does not include training in physical intervention to the same standard as door supervisors. If your venue is a licensed premises under the Licensing Act 2003, you must use SIA Door Supervisor-licensed officers, not SIA Security Guard-licensed officers. Vigil employs officers with the appropriate licence for each role and will only deploy door supervisor-licensed officers to licensed premises. Some of our officers hold both licences and can be deployed flexibly across both role types.'
  },
  {
    question: 'Do Vigil door supervisors carry out ID checks and age verification?',
    answer: 'Yes. Age verification is one of the core duties of door supervisors at any venue selling alcohol under the Licensing Act 2003. Vigil door supervisors are trained to conduct rigorous Challenge 25 age verification checks — requesting proof of age from any patron who appears to be under 25 years old. Acceptable forms of ID for age verification include a current UK or EU passport, a DVLA-issued photocard driving licence, a PASS-accredited proof of age card (such as a Portman Group card or CitizenCard), or a military ID card. Officers are trained to identify common forms of ID fraud and counterfeit documents. Any patron unable to provide acceptable ID is refused entry and offered the opportunity to return with appropriate documentation. All age verification decisions are logged, and where venues use electronic ID scanners, officers operate the equipment as part of their standard entry procedure. Maintaining robust age verification protects your premises licence and demonstrates compliance with your licence conditions to the licensing authority and the police.'
  }
]

const pageData: ServicePageData = {
  seo: {
    title:        'Door Supervisors London | SIA-Licensed Door Supervisors | Vigil',
    description:  'Door supervisors London — SIA-licensed door supervisors for licensed premises, pubs, bars, nightclubs, and events across Greater London. Directly employed, DBS-checked, £10M insured.',
    canonical:    'https://security.vigilservices.co.uk/door-supervisors-london/',
    focusKeyword: 'door supervisors london',
  },
  h1:          'Door Supervisors London',
  subheadline: 'SIA licensed. BS7858 vetted. 15-minute response. Greater London.',
  quickAnswer: 'Vigil Security Services provides door supervisors london exclusively to businesses across Greater London. Every officer is directly employed — never agency supplied.',
  intro:       '<p>Vigil Security Services works exclusively with businesses across Greater London. Every officer is directly employed by Vigil Services Ltd — SIA-licensed, BS7858 vetted, and consistently assigned to your contract.</p>',
  services:    [],
  processSteps: [
    { number: 1, title: 'Contact Vigil',
       description: 'Call or complete the enquiry form. We respond within 15 minutes.',
       timeframe: 'Within 15 minutes' },
    { number: 2, title: 'Site risk assessment',
       description: 'We visit your premises, assess your security requirements, and produce a written specification.',
       timeframe: 'Within 48 hours' },
    { number: 3, title: 'Officers deployed',
       description: 'Your directly employed, SIA-licensed team begins on your agreed start date.',
       timeframe: 'As agreed' },
  ],
  eeatPoints:    [
    { icon: '🪪', title: 'SIA-licensed officers', description: 'Every officer holds a current SIA licence in the appropriate category — Security Guarding or Door Supervision.' },
    { icon: '🔒', title: 'BS7858 vetted', description: 'Full 5-year employment history check and ID verification before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital shift reports', description: 'Timestamped shift logs and incident reports after every deployment.' },
  ],
  complianceTags: ['SIA Licensed', 'BS7858 Vetted', 'DBS Enhanced', 'Directly Employed',
                   '£10M Insured', 'PSIA 2001', 'Company Reg. 11756806'],
  boroughLinks:  [],
  faqs,
  cta: {
    primaryLabel: 'Get a security quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateServicePageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <ServicePage data={pageData} />
    </>
  )
}
