/**
 * BOROUGH PAGE — Camden
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:42:32
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172918/vigil/security/service/retail-guard-vigil-security-services-security-london.webp",
    alt:    "SIA-licensed security guard on duty at retail store entrance on Oxford Street, London",
    width:  1234,
    height: 864,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172918/vigil/security/service/retail-guard-vigil-security-services-security-london.webp",
    alt:    "SIA-licensed security guard on duty at retail store entrance on Oxford Street, London",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Camden?',
    answer: 'Vigil Security provides manned guarding, door supervision, mobile patrols, key holding and alarm response, CCTV monitoring, and event security across all Camden postcodes including NW1, NW3. Our SIA-licensed officers are deployed to hospitality venues including bars, restaurants, and nightclubs across Camden Town, King\'s Cross, and Kentish Town, event spaces and concert venues, retail premises along Camden High Street and Hampstead, corporate offices, construction sites, and residential developments. All officers are directly employed by Vigil, DBS-checked, and trained in conflict management, Licensing Act 2003 compliance, access control, and incident response. We provide both scheduled contracts and emergency callouts with 24/7 availability across Camden\'s vibrant hospitality and entertainment sectors.'
  },
  {
    question: 'Do you provide door supervision for Camden licensed premises?',
    answer: 'Yes. Camden is home to a significant concentration of licensed premises including bars, pubs, restaurants, nightclubs, and music venues, particularly across Camden Town, King\'s Cross, and Chalk Farm. All premises selling alcohol or operating as late-night venues under the Licensing Act 2003 have obligations regarding door supervision, age verification, conflict management, and incident reporting. Vigil provides SIA Door Supervision services with all officers holding current SIA Door Supervision licences and trained in age verification, refusal of entry, conflict de-escalation, first aid, and licensing law compliance. Officers work closely with venue management to maintain compliance with licence conditions and ensure safe, controlled entry and exit. We serve independent bars and restaurants, nightclubs and music venues, hotels with licensed bars, and private members\' clubs across Camden.'
  },
  {
    question: 'Do you provide event security in Camden?',
    answer: 'Yes. Camden hosts thousands of events annually including music festivals and concerts at venues like Roundhouse and Electric Ballroom, corporate events and product launches, gallery openings and private views, community festivals and street markets, and sports events. Event security requires officers trained in crowd management, emergency evacuation, access control, and conflict de-escalation. Vigil provides event security including perimeter control and ticket verification, stewarding and crowd management, VIP protection and green room security, emergency response and first aid, and post-event venue security. All officers hold SIA licences appropriate to their role and receive event-specific briefings covering site layout, emergency procedures, and client requirements. We serve event promoters, venue operators, corporate clients, and community organizations across Camden. See our dedicated event security page for detailed service specifications.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Camden | B2B Contracts | Vigil',
    description:  'Commercial security Camden. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-camden/',
    focusKeyword: 'commercial security camden',
  },
  borough:      'Camden',
  region:       'North London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Camden. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Camden. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Camden is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Camden', description: 'Scheduled security for Camden offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Camden.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Camden contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Camden quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
