/**
 * BOROUGH PAGE — Lambeth
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:50:59
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172972/vigil/security/service/security-guard-shopping-mall-security-london.webp",
    alt:    "Security guard in branded uniform and cap patrolling a retail shopping centre in London",
    width:  7500,
    height: 5000,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172972/vigil/security/service/security-guard-shopping-mall-security-london.webp",
    alt:    "Security guard in branded uniform and cap patrolling a retail shopping centre in London",
    width:  7500,
    height: 5000,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Lambeth?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and concierge services across all Lambeth postcodes including SW2, SE5, SE11, SW9. Our SIA-licensed officers serve offices and corporate premises in Vauxhall and Waterloo, retail and hospitality businesses in Brixton and Streatham, managed commercial buildings in Stockwell and Kennington, and residential developments throughout the borough. All officers are directly employed by Vigil, DBS-checked, and trained in access control, incident response, conflict management, and first aid. We provide both scheduled contracts and emergency callouts with 24/7 availability.'
  },
  {
    question: 'Are your Lambeth security officers SIA-licensed?',
    answer: 'Yes. Every officer deployed to Lambeth holds a current SIA licence in the appropriate category — Security Guarding, Door Supervision, or CCTV Operations. The Security Industry Authority regulates all frontline private security workers under the Private Security Industry Act 2001. We do not use agency staff or sub-contractors. Every guard assigned to a Lambeth contract is directly employed by Vigil Services Ltd, ensuring accountability, consistency of assignment, and adherence to our service standards. Officers are trained to understand Lambeth\'s commercial landscape — from corporate Waterloo to the independent retail and hospitality sectors of Brixton and Streatham.'
  },
  {
    question: 'Do you provide security for Brixton and Streatham retail and hospitality premises?',
    answer: 'Yes. Brixton and Streatham are priority areas for our Lambeth service. Brixton\'s independent retail, covered market, and hospitality venues require a range of security services — manned guarding with SIA Door Supervisor-licensed officers for licensed premises, loss prevention and store detective services for retail, and event security for market events and venue functions. Streatham\'s retail high street and managed commercial buildings benefit from mobile patrols, manned guarding, and key holding services. All officers deployed to Brixton and Streatham hold current SIA licences appropriate to their role and understand the operational requirements of these areas.'
  },
  {
    question: 'How quickly can you mobilise security services in Lambeth?',
    answer: 'For standard manned guarding or mobile patrol contracts in Lambeth, we typically mobilise within 48–72 hours of contract signature. This includes conducting a site risk assessment, assigning officers, completing site-specific training, and issuing uniforms and equipment. For emergency deployments — following a break-in, security incident, or sudden staffing gap — we can often deploy to Lambeth sites within 24 hours from our pool of trained relief officers. For key holding and alarm response services, we can activate your account within 24 hours once we hold your site keys and alarm codes.'
  },
  {
    question: 'Can you manage security across Lambeth and neighbouring South London boroughs?',
    answer: 'Yes. We manage multi-borough security contracts for organisations with premises across South London. If you have properties in Lambeth alongside sites in Wandsworth, Southwark, Lambeth, or other Greater London boroughs, all sites are covered by one master contract, one account manager, and unified reporting. This is the most common arrangement for commercial property managers, housing associations, and corporate occupiers with distributed South London portfolios. Consolidated billing and SLA reporting simplify procurement and compliance management.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Lambeth | B2B Contracts | Vigil',
    description:  'Commercial security Lambeth. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-lambeth',
    focusKeyword: 'commercial security lambeth',
  },
  borough:      'Lambeth',
  region:       'South London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Lambeth. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Lambeth. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Lambeth is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Lambeth', description: 'Scheduled security for Lambeth offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Lambeth.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Lambeth contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
    { name: 'Greater London', href: '/commercial-security-greater-london/', live: true },
    { name: 'Southwark', href: '/commercial-security-southwark/', live: true },
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Lambeth quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
