/**
 * BOROUGH PAGE — Hackney
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:50:57
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172972/vigil/security/service/security-guard-shopping-mall-security-london.webp",
    alt:    "Security guard in branded uniform and cap patrolling a retail shopping centre in London",
    width:  7500,
    height: 5000,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172972/vigil/security/service/security-guard-shopping-mall-security-london.webp",
    alt:    "Security guard in branded uniform and cap patrolling a retail shopping centre in London",
    width:  7500,
    height: 5000,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Hackney?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and concierge services across all Hackney postcodes including E8, N16, E9. Our SIA-licensed officers are deployed to co-working spaces, creative industry studios and offices, retail premises, tech startups, hospitality venues, construction sites, and residential developments. All officers are directly employed by Vigil, DBS-checked, and trained in access control, incident response, conflict management, and first aid. We provide both scheduled contracts and emergency callouts with 24/7 availability across Greater London including Hackney\'s vibrant commercial zones.'
  },
  {
    question: 'Are your Hackney security officers SIA-licensed?',
    answer: 'Yes. Every officer deployed to Hackney holds a current SIA licence in the appropriate category — Security Guarding, Door Supervision, or CCTV Operations. The Security Industry Authority regulates private security in the UK and mandates licensing for all frontline officers. All licences are verified at recruitment and renewed every three years. We do not use agency staff or sub-contractors. Every guard assigned to a Hackney contract is directly employed by Vigil, ensuring accountability, consistency, and adherence to our service standards. Officers deployed to Hackney understand the borough\'s mix of creative industries, co-working spaces, hospitality venues, and tech startups, and are trained to provide security that integrates with dynamic, collaborative work environments.'
  },
  {
    question: 'How quickly can you mobilise security services in Hackney?',
    answer: 'For standard manned guarding or mobile patrol contracts in Hackney, we typically mobilise within 48–72 hours of contract signature. This includes conducting a site risk assessment, assigning officers, completing site-specific training, and issuing uniforms and equipment. For emergency deployments — such as following a break-in, vandalism incident, or sudden staff absence — we maintain a pool of trained relief officers and can often deploy to Hackney sites within 24 hours. For key holding and alarm response services, we can usually activate your account within 24 hours once we hold your site keys and alarm codes. Hackney co-working spaces, studios, and tech offices often require rapid mobilisation, and we prioritise fast deployment for time-sensitive security needs.'
  },
  {
    question: 'Do you provide security for Hackney co-working spaces and creative studios?',
    answer: 'Yes. Hackney is home to a large concentration of co-working spaces, creative industry studios, tech startups, and flexible office environments, particularly around Shoreditch, Dalston, and Hackney Wick. These environments require security that balances access control with a welcoming atmosphere for members, guests, and visitors. Vigil provides manned guarding for reception and access control, mobile patrols for overnight and weekend periods, CCTV monitoring, and alarm response tailored to co-working and creative industry premises. Our officers are trained to provide professional security without creating an intimidating presence, ensuring members and guests feel safe while maintaining effective access control and incident response capabilities.'
  },
  {
    question: 'What areas of Hackney do you cover?',
    answer: 'Vigil Security covers all Hackney postcodes including E8, N16, E9 and surrounding areas. We deploy officers to commercial zones such as Shoreditch and Hoxton tech and creative industry hubs, Dalston retail and hospitality districts, Hackney Wick studios and warehouse conversions, Stoke Newington independent retail and offices, Clapton and Homerton residential and mixed-use developments, and Mare Street and Well Street town centres. Hackney is one of London\'s most diverse and rapidly evolving boroughs, and our officers are familiar with its commercial landscape, transport links, and the security challenges common to creative, tech, and hospitality-focused environments. We also serve multiple sites across Hackney and neighbouring boroughs under consolidated contracts for clients with London-wide operations.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Hackney | B2B Contracts | Vigil',
    description:  'Commercial security Hackney. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-hackney',
    focusKeyword: 'commercial security hackney',
  },
  borough:      'Hackney',
  region:       'North London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Hackney. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Hackney. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Hackney is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Hackney', description: 'Scheduled security for Hackney offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Hackney.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Hackney contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Hackney quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
