/**
 * BOROUGH PAGE — Lewisham
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:51:00
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172972/vigil/security/service/security-guard-shopping-mall-security-london.webp",
    alt:    "Security guard in branded uniform and cap patrolling a retail shopping centre in London",
    width:  7500,
    height: 5000,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172972/vigil/security/service/security-guard-shopping-mall-security-london.webp",
    alt:    "Security guard in branded uniform and cap patrolling a retail shopping centre in London",
    width:  7500,
    height: 5000,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What commercial security services does Vigil provide in Lewisham?',
    answer: 'Vigil Security provides manned guarding, mobile patrols, key holding and alarm response, CCTV monitoring, event security, and retail security across all Lewisham postcodes including SE13, SE6, SE4, SE8, SE14. Our SIA-licensed officers serve managed commercial buildings in Lewisham and Catford, retail premises along Lewisham High Street and Catford shopping areas, creative and arts venues in Deptford and New Cross, and construction sites and residential developments across the borough. All officers are directly employed by Vigil Services Ltd, DBS-checked, and trained in access control, incident response, and conflict management.'
  },
  {
    question: 'Are your Lewisham security officers SIA-licensed?',
    answer: 'Yes. Every officer deployed to Lewisham holds a current SIA licence appropriate to their role — Security Guarding, Door Supervision, or CCTV Operations. Under the Private Security Industry Act 2001, all frontline private security personnel must hold a valid SIA licence. We do not use agency staff or sub-contractors — every officer assigned to Lewisham contracts is directly employed by Vigil Services Ltd, ensuring consistent assignment and accountability. Officers are trained to understand Lewisham\'s commercial landscape, from Lewisham and Catford town centres to the arts and creative sector in Deptford and New Cross.'
  },
  {
    question: 'Do you provide security for Deptford and New Cross premises?',
    answer: 'Yes. Deptford and New Cross are core areas in our Lewisham service. The area has a significant arts, creative industries, and independent hospitality sector, alongside managed commercial buildings and residential developments. We provide manned guarding and door supervision for licensed premises and event venues in Deptford and New Cross, mobile patrols for commercial properties and construction sites, and key holding and alarm response for businesses and managed buildings. Officers understand the operational requirements of creative and arts-focused venues where security must balance effective access control with a welcoming atmosphere.'
  },
  {
    question: 'How quickly can you mobilise security services in Lewisham?',
    answer: 'For standard manned guarding or mobile patrol contracts in Lewisham, we typically mobilise within 48–72 hours of contract signature. For emergency deployments following a security incident or staffing emergency, we can often deploy to Lewisham sites within 24 hours. For key holding and alarm response, we can activate your account within 24 hours once we hold your keys and alarm codes. Lewisham is well within our South and South-East London coverage zone, and we maintain officer availability across the area for rapid mobilisation.'
  },
  {
    question: 'Can you manage security contracts across Lewisham and neighbouring boroughs?',
    answer: 'Yes. We manage multi-borough security contracts for organisations with premises across South-East London. If you have properties in Lewisham alongside sites in Greenwich, Southwark, Lambeth, or other Greater London boroughs, all sites are covered by one master contract, one account manager, and unified SLA reporting. This is the most common arrangement for commercial property managers and housing associations managing distributed South-East London portfolios. Consolidated billing simplifies procurement and ensures consistent service standards across all sites.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Lewisham | B2B Contracts | Vigil',
    description:  'Commercial security Lewisham. Directly employed. DBS checked. 15-minute response.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-lewisham',
    focusKeyword: 'commercial security lewisham',
  },
  borough:      'Lewisham',
  region:       'South London',
  postcodes:    [],
  h1:           'Commercial Security',
  quickAnswer:  'Vigil provides directly employed commercial security across Lewisham. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Lewisham. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Lewisham is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Lewisham', description: 'Scheduled security for Lewisham offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Lewisham.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Lewisham contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
    { name: 'Greater London', href: '/commercial-security-greater-london/', live: true },
    { name: 'Southwark', href: '/commercial-security-southwark/', live: true },
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Lewisham quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
