/**
 * BOROUGH PAGE — Greater London
 * Template: BoroughPage v1.0 — June 2026
 * Images: assign via app.vigilservices.co.uk/admin/pages
 */

import { Metadata }   from 'next'
import BoroughPage     from '@/components/templates/BoroughPage'
import { generateBoroughPageSchema } from '@/lib/schema/borough-page-schema'
import type { BoroughPageData, FAQ } from '@/types/page-templates'

// IMAGES BLOCK — generated by CRM Page Manager
// 2026-06-23 00:50:56
// Manage at: app.vigilservices.co.uk/admin/pages
const images: BoroughPageData["images"] = {
  hero: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172878/vigil/security/service/construction-site-security-london-vigil-security-services-security-london.webp",
    alt:    "Vigil security officer in hi-vis jacket with SIA licence and CSCS hard hat using handheld device at London construction site",
    width:  1234,
    height: 864,
    priority: true,
  },
  service: {
    src:    "/placeholder-image.svg",
    alt:    "Service in borough — assign via CRM",
    width:  600,
    height: 400,
  },
  local: {
    src:    "/placeholder-image.svg",
    alt:    "Local area image — assign via CRM",
    width:  600,
    height: 400,
  },
  trust: {
    src:    "/placeholder-image.svg",
    alt:    "Trust / team image — assign via CRM",
    width:  500,
    height: 500,
  },
  og: {
    src:    "https://res.cloudinary.com/duhicmygg/image/upload/v1782172878/vigil/security/service/construction-site-security-london-vigil-security-services-security-london.webp",
    alt:    "Vigil security officer in hi-vis jacket with SIA licence and CSCS hard hat using handheld device at London construction site",
    width:  1234,
    height: 864,
  },
}

const faqs: FAQ[] = [
  {
    question: 'What areas of Greater London does Vigil Security cover?',
    answer: 'Vigil Security operates across Greater London from central London financial districts (City of London, Canary Wharf, Westminster) through inner London (Camden, Islington, Hackney, Tower Hamlets, Southwark) to outer London boroughs (Barnet, Bromley, Croydon, Ealing, and all others). We deploy SIA-licensed officers to commercial offices, retail premises, construction sites, hospitality venues, healthcare facilities, educational institutions, and residential developments. All officers are directly employed by Vigil, DBS-checked, and familiar with Greater London geography including transport links, commercial zones, and borough-specific environments. If you operate multiple sites across Greater London, we provide consolidated security contracts with a single account manager, unified reporting, and consistent service standards regardless of borough.'
  },
  {
    question: 'Do you provide security for multi-site organisations across Greater London?',
    answer: 'Yes. Many of our clients operate multiple sites across Greater London including retail chains with stores in several boroughs, property management companies with residential portfolios, construction contractors with simultaneous projects, and corporate organisations with offices in multiple locations. Vigil provides consolidated security contracts covering all your Greater London sites under a single agreement with one account manager, unified reporting across all locations, consistent service standards regardless of borough, centralised invoicing and administration, and coordinated officer deployment and management. This simplifies procurement, reduces administrative overhead, and ensures your security standards are maintained consistently across your entire Greater London operation. We currently serve multi-site clients with locations spanning 5+ boroughs under single consolidated contracts.'
  },
  {
    question: 'What commercial security services does Vigil provide across Greater London?',
    answer: 'Vigil provides comprehensive commercial security services across Greater London including manned guarding for offices, retail premises, construction sites, and events with SIA-licensed officers stationed on-site during contracted hours, mobile patrols for unoccupied properties and construction sites with GPS-tracked visits and auditable proof of attendance, key holding and alarm response for out-of-hours alarm activations with response times typically under 20 minutes, door supervision for licensed premises under Licensing Act 2003 obligations, CCTV monitoring from on-site control rooms or client premises, event security for concerts, festivals, corporate functions, and private events, construction site security including CDM 2015 compliant gatehouse, patrols, and tool audits, and concierge security for residential developments combining reception services with security oversight. All services are available 24/7 across all Greater London boroughs with emergency callout capability.'
  }
]

const pageData: BoroughPageData = {
  seo: {
    title:        'Commercial Security Greater London | B2B Contracts | Vigil',
    description:  'SIA-licensed commercial security services across Greater London.',
    canonical:    'https://security.vigilservices.co.uk/commercial-security-greater-london',
    focusKeyword: 'commercial security greater london',
  },
  borough:      'Greater London',
  region:       'Greater London',
  postcodes:    [],
  h1:           'Commercial Security Greater London',
  quickAnswer:  'Vigil provides directly employed commercial security across Greater London. 15-minute response. DBS checked operatives. Digital proof of service on every visit.',
  intro:        '<p>Vigil Security Services works exclusively with businesses across Greater London. Every operative is directly employed by Vigil Services Ltd — consistent assignment means the same team on every visit, familiar with your building and standards.</p>',
  localContext: '<p>Greater London is one of London\'s key commercial areas. We cover the full borough — offices, managed properties, retail premises, and public venues. Vigil responds to every client query within 15 minutes.</p>',
  services:     [
    { icon: '🏢', title: 'Office security Greater London', description: 'Scheduled security for Greater London offices.', href: '/manned-guarding-london/' },
    { icon: '🏘️', title: 'Property management', description: 'Multi-site portfolio security across Greater London.', href: '/property-management-security-london/' },
  ],
  eeatPoints:   [
    { icon: '✓', title: 'Directly employed operatives', description: 'No agency staff on Greater London contracts. Consistent assignment every visit.' },
    { icon: '🔒', title: 'DBS Enhanced checked', description: 'Every operative holds a current Enhanced DBS certificate before deployment.' },
    { icon: '⚡', title: '15-minute response', description: 'Every client query answered within 15 minutes — throughout the contract.' },
    { icon: '📋', title: 'Digital proof of service', description: 'Every visit digitally documented. Monthly SLA reports as standard.' },
  ],
  nearbyBoroughs: [
  ],
  faqs,
  cta: {
    primaryLabel: 'Get a Greater London quote',
    primaryUrl:   'https://app.vigilservices.co.uk/enquire/security',
    phone:        '020 3973 8892',
    phoneLabel:   'Call 020 3973 8892',
  },
  images,
}

export const metadata: Metadata = {
  title:       pageData.seo.title,
  description: pageData.seo.description,
  alternates:  { canonical: pageData.seo.canonical },
  openGraph: {
    title:       pageData.seo.title,
    description: pageData.seo.description,
    url:         pageData.seo.canonical,
    locale:      'en_GB',
    images: [{ url: images.og.src, width: 1200,
               height: 630, alt: images.og.alt }],
  },
}

export default function Page() {
  const schema = generateBoroughPageSchema(pageData, 'security')
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <BoroughPage data={pageData} division="security" />
    </>
  )
}
